apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: director@blaze.su
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers: 
      - http01:
          ingress:
            class: nginx
      - dns01:
        cloudflare:
          email: director@blaze.su
          apiKeySecretRef:
            name: cloudflare-apikey-secret
            key: apikey
        selector:
          dnsZones:
          - k8s.blaze.su      


