apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsenscrypt.org/directory
    email: 'director@blaze.su'
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}


