apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: k8s-blaze-su
spec:
  secretName: k8s-blaze-su-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: k8s.blaze.su
  dnsNames:
    - k8s.blaze.su
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - k8s.blaze.su